In [ ]:
# install the tools you will use later
!pip install --upgrade setuptools
!pip install --upgrade pip
!pip install nashpy
!pip install quantecon

/bin/bash: line 1: pip: command not found
/bin/bash: line 1: pip: command not found
/bin/bash: line 1: pip: command not found
/bin/bash: line 1: pip: command not found


In [ ]:
import numpy as np
import nashpy as nash

def divide_dollar_game(T=6, step=1, d1=0, d2=0): #T=total pool
    """
    A divide-the-dollar (Nash demand) game on grid {0, step, ..., T}.
    If i+j <= T -> payoffs (i, j); else -> (d1, d2) (disagreement payoffs).
    Returns: demands_grid, game
    """
    demands = np.arange(0, T+1, step)
    I, J = np.meshgrid(demands, demands, indexing="ij")
    feasible = (I + J) <= T
    A = np.where(feasible, I, d1)  # Row player's payoff
    B = np.where(feasible, J, d2)  # Column player's payoff
    return demands, nash.Game(A, B)

ModuleNotFoundError: No module named 'nashpy'

In [ ]:
demands, G = divide_dollar_game(T=4, step=1)
list(G.support_enumeration())

/usr/local/lib/python3.12/dist-packages/nashpy/algorithms/support_enumeration.py:260: RuntimeWarning: 
An even number of (186) equilibria was returned. This
indicates that the game is degenerate. Consider using another algorithm
to investigate.
                  
  warnings.warn(warning, RuntimeWarning)


[(array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
  array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.])),
 (array([0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
  array([0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.])),
 (array([0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.]),
  array([0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.]))]

In [ ]:
'''the result of the last step with a 50 total and 5 coins per step: RuntimeWarning:
An even number of (186) equilibria was returned. This
indicates that the game is degenerate. Consider using another algorithm
to investigate.

  warnings.warn(warning, RuntimeWarning)
[(array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
  array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.])),
 (array([0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
  array([0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.])),
 (array([0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.]),
  array([0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.]))] '''

'the result of the last step: RuntimeWarning: \nAn even number of (186) equilibria was returned. This\nindicates that the game is degenerate. Consider using another algorithm\nto investigate.\n                  \n  warnings.warn(warning, RuntimeWarning)\n[(array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),\n  array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.])),\n (array([0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),\n  array([0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.])),\n (array([0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.]),\n  array([0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.]))] '